version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_user -d portfolio_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  portfolio-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3000
      DATABASE_URL: postgresql://portfolio_user:portfolio_password@postgres:5432/portfolio_db
      UPLOAD_DIR: /uploads
      API_KEY: your-secret-api-key-change-in-production
      RUST_LOG: info
    volumes:
      - ./uploads:/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
