# Docker Compose configuration for Portfolio Server

version: "3.8"

services:
  portfolio-server:
    build: .
    container_name: portfolio-server
    ports:
      - "3000:3000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - DATABASE_URL=sqlite:./data/portfolio.db
      - UPLOAD_DIR=./uploads
      - API_KEY=your-secret-api-key-change-in-production
      - RUST_LOG=info
    volumes:
      # Persist database and uploads
      - portfolio_data:/app/data
      - portfolio_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/albums",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: portfolio-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - portfolio-server
  #   restart: unless-stopped

volumes:
  portfolio_data:
    driver: local
  portfolio_uploads:
    driver: local

networks:
  default:
    name: portfolio-network
